# .devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/cpp:latest

# Example: install cmake and other stuff
RUN apt-get update && \
    apt-get install -y cmake ninja-build

# Any other customizations you need...
